<!DOCTYPE ideg
[
<!ELEMENT ideg    ( dog, cat, catowner+ )>
<!ELEMENT dog     ( #PCDATA )>
<!ELEMENT cat      ( #PCDATA )>
<!ELEMENT catowner ( #PCDATA )>
<!ATTLIST dog  id ID #REQUIRED >
<!ATTLIST cat   id ID #REQUIRED >
<!ATTLIST catowner  pet IDREF #REQUIRED>
]><ideg>
        <dog  id="danny"            >Danny</dog>
        <cat   id="bede"              >Bede</cat>
        <cat   id="poochi"              >Bede</cat>
        <catowner pet="poochi" >Fumiaki</catowner>
        <catowner pet="bede"    >Rick</catowner>
</ideg>